# Generated by Django 3.1.4 on 2020-12-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveimage', '0002_auto_20201220_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Высота'),
        ),
    ]
